name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout mruby
      run: git clone https://github.com/mruby/mruby.git
    - name: copy config file
      run: cp .github/workflows/custom_config.rb mruby/
    - run: cat mruby/custom_config.rb
    - name: run build and test
      run: cd mruby && MRUBY_CONFIG=./custom_config.rb ASAN_OPTIONS=detect_leaks=0 ./minirake all test
