name: mrbgem test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        mruby_version: [2.1.2, 2.1.0, 2.0.0, 1.4.1, 1.2.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: checkout mruby
      run: git clone https://github.com/mruby/mruby.git
    - name: copy config file
      run: cp .github/workflows/custom_config.rb mruby/
    - run: cat mruby/custom_config.rb
    - name: run build and test
      run: cd mruby && MRUBY_CONFIG=./custom_config.rb ASAN_OPTIONS=detect_leaks=0 ./minirake all test
